//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab6.FlightService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Flight", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Flight : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string toField;
        
        private int durationMinutesField;
        
        private System.DateTime startTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string from {
            get {
                return this.fromField;
            }
            set {
                if ((object.ReferenceEquals(this.fromField, value) != true)) {
                    this.fromField = value;
                    this.RaisePropertyChanged("from");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string to {
            get {
                return this.toField;
            }
            set {
                if ((object.ReferenceEquals(this.toField, value) != true)) {
                    this.toField = value;
                    this.RaisePropertyChanged("to");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int durationMinutes {
            get {
                return this.durationMinutesField;
            }
            set {
                if ((this.durationMinutesField.Equals(value) != true)) {
                    this.durationMinutesField = value;
                    this.RaisePropertyChanged("durationMinutes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime startTime {
            get {
                return this.startTimeField;
            }
            set {
                if ((this.startTimeField.Equals(value) != true)) {
                    this.startTimeField = value;
                    this.RaisePropertyChanged("startTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Place", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Place : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int FlightIdField;
        
        private int placeNumberField;
        
        private int priceField;
        
        private int idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int FlightId {
            get {
                return this.FlightIdField;
            }
            set {
                if ((this.FlightIdField.Equals(value) != true)) {
                    this.FlightIdField = value;
                    this.RaisePropertyChanged("FlightId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int placeNumber {
            get {
                return this.placeNumberField;
            }
            set {
                if ((this.placeNumberField.Equals(value) != true)) {
                    this.placeNumberField = value;
                    this.RaisePropertyChanged("placeNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int price {
            get {
                return this.priceField;
            }
            set {
                if ((this.priceField.Equals(value) != true)) {
                    this.priceField = value;
                    this.RaisePropertyChanged("price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FlightService.MyFlightsServiceSoap")]
    public interface MyFlightsServiceSoap {
        
        // CODEGEN: Контракт генерации сообщений с именем getFlightsResult из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getFlights", ReplyAction="*")]
        lab6.FlightService.getFlightsResponse getFlights(lab6.FlightService.getFlightsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getFlights", ReplyAction="*")]
        System.Threading.Tasks.Task<lab6.FlightService.getFlightsResponse> getFlightsAsync(lab6.FlightService.getFlightsRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем getPlacesOnResult из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getPlacesOn", ReplyAction="*")]
        lab6.FlightService.getPlacesOnResponse getPlacesOn(lab6.FlightService.getPlacesOnRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getPlacesOn", ReplyAction="*")]
        System.Threading.Tasks.Task<lab6.FlightService.getPlacesOnResponse> getPlacesOnAsync(lab6.FlightService.getPlacesOnRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buyTicketOn", ReplyAction="*")]
        bool buyTicketOn(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buyTicketOn", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> buyTicketOnAsync(int id);
        Flight[] getFlights();
        Place[] getPlacesOn(int id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getFlightsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getFlights", Namespace="http://tempuri.org/", Order=0)]
        public lab6.FlightService.getFlightsRequestBody Body;
        
        public getFlightsRequest() {
        }
        
        public getFlightsRequest(lab6.FlightService.getFlightsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getFlightsRequestBody {
        
        public getFlightsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getFlightsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getFlightsResponse", Namespace="http://tempuri.org/", Order=0)]
        public lab6.FlightService.getFlightsResponseBody Body;
        
        public getFlightsResponse() {
        }
        
        public getFlightsResponse(lab6.FlightService.getFlightsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getFlightsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public lab6.FlightService.Flight[] getFlightsResult;
        
        public getFlightsResponseBody() {
        }
        
        public getFlightsResponseBody(lab6.FlightService.Flight[] getFlightsResult) {
            this.getFlightsResult = getFlightsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPlacesOnRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPlacesOn", Namespace="http://tempuri.org/", Order=0)]
        public lab6.FlightService.getPlacesOnRequestBody Body;
        
        public getPlacesOnRequest() {
        }
        
        public getPlacesOnRequest(lab6.FlightService.getPlacesOnRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getPlacesOnRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int FId;
        
        public getPlacesOnRequestBody() {
        }
        
        public getPlacesOnRequestBody(int FId) {
            this.FId = FId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPlacesOnResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPlacesOnResponse", Namespace="http://tempuri.org/", Order=0)]
        public lab6.FlightService.getPlacesOnResponseBody Body;
        
        public getPlacesOnResponse() {
        }
        
        public getPlacesOnResponse(lab6.FlightService.getPlacesOnResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getPlacesOnResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public lab6.FlightService.Place[] getPlacesOnResult;
        
        public getPlacesOnResponseBody() {
        }
        
        public getPlacesOnResponseBody(lab6.FlightService.Place[] getPlacesOnResult) {
            this.getPlacesOnResult = getPlacesOnResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MyFlightsServiceSoapChannel : lab6.FlightService.MyFlightsServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyFlightsServiceSoapClient : System.ServiceModel.ClientBase<lab6.FlightService.MyFlightsServiceSoap>, lab6.FlightService.MyFlightsServiceSoap {
        
        public MyFlightsServiceSoapClient() {
        }
        
        public MyFlightsServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyFlightsServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyFlightsServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyFlightsServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        lab6.FlightService.getFlightsResponse lab6.FlightService.MyFlightsServiceSoap.getFlights(lab6.FlightService.getFlightsRequest request) {
            return base.Channel.getFlights(request);
        }
        
        public lab6.FlightService.Flight[] getFlights() {
            lab6.FlightService.getFlightsRequest inValue = new lab6.FlightService.getFlightsRequest();
            inValue.Body = new lab6.FlightService.getFlightsRequestBody();
            lab6.FlightService.getFlightsResponse retVal = ((lab6.FlightService.MyFlightsServiceSoap)(this)).getFlights(inValue);
            return retVal.Body.getFlightsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<lab6.FlightService.getFlightsResponse> lab6.FlightService.MyFlightsServiceSoap.getFlightsAsync(lab6.FlightService.getFlightsRequest request) {
            return base.Channel.getFlightsAsync(request);
        }
        
        public System.Threading.Tasks.Task<lab6.FlightService.getFlightsResponse> getFlightsAsync() {
            lab6.FlightService.getFlightsRequest inValue = new lab6.FlightService.getFlightsRequest();
            inValue.Body = new lab6.FlightService.getFlightsRequestBody();
            return ((lab6.FlightService.MyFlightsServiceSoap)(this)).getFlightsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        lab6.FlightService.getPlacesOnResponse lab6.FlightService.MyFlightsServiceSoap.getPlacesOn(lab6.FlightService.getPlacesOnRequest request) {
            return base.Channel.getPlacesOn(request);
        }
        
        public lab6.FlightService.Place[] getPlacesOn(int FId) {
            lab6.FlightService.getPlacesOnRequest inValue = new lab6.FlightService.getPlacesOnRequest();
            inValue.Body = new lab6.FlightService.getPlacesOnRequestBody();
            inValue.Body.FId = FId;
            lab6.FlightService.getPlacesOnResponse retVal = ((lab6.FlightService.MyFlightsServiceSoap)(this)).getPlacesOn(inValue);
            return retVal.Body.getPlacesOnResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<lab6.FlightService.getPlacesOnResponse> lab6.FlightService.MyFlightsServiceSoap.getPlacesOnAsync(lab6.FlightService.getPlacesOnRequest request) {
            return base.Channel.getPlacesOnAsync(request);
        }
        
        public System.Threading.Tasks.Task<lab6.FlightService.getPlacesOnResponse> getPlacesOnAsync(int FId) {
            lab6.FlightService.getPlacesOnRequest inValue = new lab6.FlightService.getPlacesOnRequest();
            inValue.Body = new lab6.FlightService.getPlacesOnRequestBody();
            inValue.Body.FId = FId;
            return ((lab6.FlightService.MyFlightsServiceSoap)(this)).getPlacesOnAsync(inValue);
        }
        
        public bool buyTicketOn(int id) {
            return base.Channel.buyTicketOn(id);
        }
        
        public System.Threading.Tasks.Task<bool> buyTicketOnAsync(int id) {
            return base.Channel.buyTicketOnAsync(id);
        }
    }
}
